#端口
server:
  port: 10001

spring:
  #服务名(不配置，服务注册不成功)
  application:
    name: zhixingmall-product

  #配置数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://150.158.135.181:3306/zhixingmall_pms?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

  #注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.135.181:8848
    alicloud:
      access-key: LTAI4FzhuX1rFQt2yWDmgwsn
      secret-key: z3ZFoNHoCaG1V1qmQ32Dm4OTLNP5fA
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false   #关闭thymeleaf缓存
  redis:
    host: 150.158.135.181
    port: 6379
  session:
    store-type: redis   #指定session的存储格式

  cache:
    type: redis
    redis:
      time-to-live: 3600000  #毫秒为单位
#      key-prefix: CACHE_   #如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      cache-null-values: true   #是否缓存空值，防止缓存穿透

#    cache-names: qq

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 配置mybatis-plus的映射文件
  global-config:
    db-config:
      id-type: auto  #配置每个实体类的主键自增长
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.atguigu.gulimall: debug

#线程池属性的配置
gulimall:
  thread:
    core: 20
    max-size: 200
    keep-alive-time: 10

