#端口
server:
  port: 8000

spring:
  #服务名
  application:
    name: zhixingmall-member

  #配置数据源
  datasource:
    username: root
    password: root
    url: jdbc:mysql://150.158.135.181:3306/zhixingmall_ums?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

  #注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.135.181:8848

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 配置mybatis-plus的映射文件
  global-config:
    db-config:
      id-type: auto  #配置每个实体类的主键自增长
      logic-delete-value: 1
      logic-not-delete-value: 0